#!/bin/zsh

Color_Off='\033[0m'
Green='\033[0;32m'
Yellow='\033[0;33m'
White='\033[0;37m'
BYELLOW='\033[1;33m'
Red='\033[0;31m'
BRed='\033[1;31m'
Cyan='\033[0;36m'

info() { [[ -n $* ]] && echo -e "${Yellow}ℹ $1${Color_Off}"; }
info_custom() { [[ -n $* ]] && echo -e "$1${Color_Off}"; }
error() { echo -e "${BRed}❌ Error:${Color_Off} $*" 1>&2; }
_die() { error "$*"; exit 1; }
read_config() { if [[ "$NON_INTERACTIVE" == 1 ]]; then typeset -g "$2"="$3"; return; fi; if [[ -n $* ]]; then local ANSWER; echo -n -e "${White}❓ $1 [${Green}$3${White}]: ${Color_Off}"; read -r ANSWER; typeset -g "$2"="${ANSWER:-$3}"; fi }
read_input()  { if [[ "$NON_INTERACTIVE" == 1 ]]; then typeset -g "$2"="$3"; return; fi; if [[ -n $* ]]; then local ANSWER; echo -n -e "${White}❓ $1: ${Color_Off}"; read -r ANSWER; typeset -g "$2"="${ANSWER}"; fi }
read_password(){ if [[ "$NON_INTERACTIVE" == 1 ]]; then typeset -g "$2"="$3"; return; fi; if [[ -n $* ]]; then local ANSWER; echo -n -e "${White}❓ $1: ${Color_Off}"; read -rs ANSWER; echo -e ""; typeset -g "$2"="${ANSWER}"; fi }

if ! docker info >/dev/null 2>&1; then
  _die "Docker is not running or not accessible. Please start Docker and try again."
fi

IMAGE_NAME=liferay/dxp
PROJECT_META_FILE=".liferay-docker.meta"

NON_INTERACTIVE=0
QUIET=0
VERBOSE=0
RUN_LIST=0
ROOT_ARG=""
TAG_ARG=""
CONTAINER_ARG=""
RELEASE_TYPE_ARG=""
DB_KIND=""
JDBC_USERNAME_ARG=""
JDBC_PASSWORD_ARG=""
RECREATE_DB_FLAG=""
HOST_NETWORK_FLAG=""
NO_HOST_NETWORK_FLAG=""
DISABLE_ZIP64_FLAG_EXPL=""
PORT_ARG=""
REMOVE_AFTER_FLAG=""
KEEP_CONTAINER_FLAG=""
DELETE_STATE_FLAG=""

read_meta() {
  local file="$1"
  local key="$2"
  if [[ -f "$file" ]]; then
    grep "^$key=" "$file" | cut -d'=' -f2-
  fi
}

write_meta() {
  local file="$1"
  local key="$2"
  local val="$3"
  if [[ ! -f "$file" ]]; then
    echo "# Generated by Liferay Docker Manager ($(date -Iseconds))" > "$file"
  fi
  if grep -q "^$key=" "$file"; then
    # Use a temp file for portability with sed
    local tmpfile=$(mktemp)
    sed "s|^$key=.*|$key=$val|" "$file" > "$tmpfile" && mv "$tmpfile" "$file"
  else
    echo "$key=$val" >> "$file"
  fi
}

discover_latest_tag() {
  local query_url="$1"
  local year_filter="$2"
  local release_type="$3"

  local url="$query_url"
  local tags=()

  if [[ $VERBOSE -eq 1 ]]; then
    echo -e "${Yellow}ℹ Discovering latest Docker tag for release type ${BYellow}${release_type}${Yellow} with year filter ${BYellow}${year_filter:-none}${Yellow}${Color_Off}" >&2
  fi

  while [[ -n "$url" ]]; do
    local json
    json=$(curl -s "$url") || break

    local names
    names=("${(@f)$(echo "$json" | jq -r '.results[].name')}")

    local name
    for name in "${names[@]}"; do
      [[ -z "$name" ]] && continue

      if [[ -n "$year_filter" && "$name" != ${year_filter}.* ]]; then
        continue
      fi

      case "$release_type" in
        lts)
          [[ "$name" =~ ^[0-9]{4}\.q[1-4]\.[0-9]+-lts$ ]] || continue
          ;;
        u)
          [[ "$name" =~ ^[0-9]{4}\.q[1-4]\.[0-9]+-u[0-9]+$ ]] || continue
          ;;
        qr)
          [[ "$name" =~ ^[0-9]{4}\.q[1-4]\.[0-9]+$ ]] || continue
          ;;
        any|*)
          [[ "$name" =~ ^[0-9]{4}\.q[1-4]\.[0-9]+(-u[0-9]+|-lts)?$ ]] || continue
          ;;
      esac

      tags+=("$name")
    done

    url=$(echo "$json" | jq -r '.next // empty')
  done

  if (( ${#tags[@]} == 0 )); then
    [[ $VERBOSE -eq 1 ]] && echo -e "${Yellow}ℹ No matching Docker tags found${Color_Off}" >&2
    echo ""
  else
    local latest_tag
    latest_tag=$(printf '%s\n' "${tags[@]}" | sort -V | tail -n1)
    if [[ $VERBOSE -eq 1 ]]; then
      echo -e "${Yellow}ℹ Auto-detected Docker tag: ${BYellow}${latest_tag}${Color_Off}" >&2
    fi
    echo "$latest_tag"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --list) RUN_LIST=1 ;;
    -r|--root) shift; [[ -z "$1" ]] && _die "--root requires a path"; ROOT_ARG="$1" ;;
    -t|--tag) shift; [[ -z "$1" ]] && _die "--tag requires a value"; TAG_ARG="$1" ;;
    -c|--container) shift; [[ -z "$1" ]] && _die "--container requires a name"; CONTAINER_ARG="$1" ;;
    --release-type) shift; [[ -z "$1" ]] && _die "--release-type requires any|u|lts|qr"; case "${1:l}" in any|u|lts|qr) RELEASE_TYPE_ARG="${1:l}" ;; *) _die "--release-type must be any|u|lts|qr";; esac ;;
    --non-interactive) NON_INTERACTIVE=1 ;;
    --db) shift; [[ -z "$1" ]] && _die "--db requires postgresql|mysql|hypersonic"; case "${1:l}" in postgresql|mysql|hypersonic) DB_KIND="${1:l}" ;; *) _die "--db must be postgresql|mysql|hypersonic";; esac ;;
    --hypersonic) DB_KIND="hypersonic" ;;
    --jdbc-username) shift; [[ -z "$1" ]] && _die "--jdbc-username requires a value"; JDBC_USERNAME_ARG="$1" ;;
    --jdbc-password) shift; [[ -z "$1" ]] && _die "--jdbc-password requires a value"; JDBC_PASSWORD_ARG="$1" ;;
    --recreate-db) RECREATE_DB_FLAG=1 ;;
    --host-network) HOST_NETWORK_FLAG=1 ;;
    --no-host-network) NO_HOST_NETWORK_FLAG=1 ;;
    --disable-zip64) DISABLE_ZIP64_FLAG_EXPL=1 ;;
    -p|--port) shift; [[ -z "$1" || "$1" != <-> ]] && _die "--port requires a number"; PORT_ARG="$1" ;;
    --remove-after) REMOVE_AFTER_FLAG=1 ;;
    --keep-container) KEEP_CONTAINER_FLAG=1 ;;
    --delete-state) DELETE_STATE_FLAG=1 ;;
    --quiet) QUIET=1 ;;
    --verbose) VERBOSE=1 ;;
    -h|--help)
      echo "Usage: $0 [options]";
      echo "";
      echo "Core paths and image:";
      echo "      --list                    List available DXP folders and select one";
      echo "  -t, --tag <tag>               Liferay Docker image tag. Default: latest tag for chosen release type";
      echo "  -r, --root <path>             Project root. Default: ./<tag>";
      echo "  -c, --container <name>        Container name. Default: basename(<root>) with dots replaced by dashes";
      echo "      --release-type any|u|lts|qr  Tag discovery mode. Default: any";
      echo "";
      echo "Database selection:";
      echo "      --db postgresql|mysql|hypersonic  Database choice. Default: prompt; non-interactive defaults to hypersonic unless JDBC opts provided";
      echo "      --jdbc-username <name>    Username for external DB";
      echo "      --jdbc-password <pass>    Password for external DB";
      echo "      --recreate-db             Drop and recreate the target database if it exists";
      echo "";
      echo "Runtime behavior:";
      echo "  -p, --port <8080>             Local HTTP port mapping. Default: 8080";
      echo "      --host-network|--no-host-network  Use or avoid host networking. Default: disabled";
      echo "      --disable-zip64           Disable Zip64 extra field validation. Default: enabled";
      echo "      --remove-after|--keep-container   Remove container after run or keep it. Default: keep when created, stop when kept";
      echo "      --delete-state             When container already exists, delete osgi/state before starting";
      echo "      --non-interactive         Do not prompt; apply defaults and provided flags";
      echo "      --quiet | --verbose       Adjust logging";
      exit 0 ;;
    *) _die "Unknown option: $1" ;;
  esac
  shift
done

if [[ $RUN_LIST -eq 1 ]]; then
  folders=()
  versions=()
  for d in */; do
    d=${d%/}
    if [[ -d "$d/files" || -d "$d/deploy" ]]; then
       if [[ "$d" != "7.4-common" && "$d" != .* ]]; then
         folders+=("$d")
         ver=$(read_meta "$d/$PROJECT_META_FILE" "tag")
         versions+=("${ver:-unknown}")
       fi
    fi
  done

  info_custom "${BYELLOW}=== Available DXP Folders ==="
  if (( ${#folders[@]} > 0 )); then
    for i in {1..${#folders[@]}}; do
      info_custom "${White}[$i] ${folders[$i]} [${Cyan}${versions[$i]}${White}]"
    done
  fi
  info_custom "${White}[$((${#folders[@]} + 1))] Create New..."

  read_config "Select folder index" CHOICE_IDX 1
  if [[ "$CHOICE_IDX" -gt 0 && "$CHOICE_IDX" -le ${#folders[@]} ]]; then
    LIFERAY_ROOT="${folders[$CHOICE_IDX]}"
    ROOT_ARG="$LIFERAY_ROOT"
  elif [[ "$CHOICE_IDX" -eq $((${#folders[@]} + 1)) ]]; then
    ROOT_ARG=""
    TAG_ARG=""
  else
    _die "Invalid selection."
  fi
fi

# Initial root path detection
if [[ -n "$ROOT_ARG" ]]; then
  LIFERAY_ROOT="$ROOT_ARG"
else
  # If no root arg but we have a tag, default to ./tag
  if [[ -n "$TAG_ARG" ]]; then
    LIFERAY_ROOT_DEFAULT=./${TAG_ARG}
  else
    LIFERAY_ROOT_DEFAULT=""
  fi
fi

# Read existing metadata if root exists
if [[ -n "$LIFERAY_ROOT" && -d "$LIFERAY_ROOT" ]]; then
  META_TAG=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "tag")
  META_PORT=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "port")
  META_DB=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "db_type")
  META_CONTAINER=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "container_name")
  META_HOSTNET=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "host_network")
fi

# Resolve Tag
if [[ -n "$TAG_ARG" ]]; then
  LIFERAY_TAG="$TAG_ARG"
else
  LIFERAY_TAG=${META_TAG}
  if [[ -z "$LIFERAY_TAG" ]]; then
    API_BASE='https://hub.docker.com/v2/repositories/liferay/dxp/tags?page_size=200&ordering=name'
    if [[ -n "$RELEASE_TYPE_ARG" ]]; then
      RELEASE_TYPE="$RELEASE_TYPE_ARG"
    else
      if [[ $NON_INTERACTIVE -eq 1 ]]; then
        RELEASE_TYPE=any
      else
        read_config "Release type (any|u|lts|qr) or Enter Tag" RELEASE_TYPE any
      fi

      if [[ "$RELEASE_TYPE" =~ ^[0-9]{4}\.q[1-4]\.[0-9]+(-u[0-9]+|-lts)?$ ]]; then
        LIFERAY_TAG="$RELEASE_TYPE"
      else
        case "${RELEASE_TYPE:l}" in
          lts) QUERY_URL="$API_BASE&name=-lts" ;;
          u) QUERY_URL="$API_BASE&name=-u" ;;
          *) QUERY_URL="$API_BASE" ;;
        esac

        YEAR_FILTER=$(date +%Y)
        LIFERAY_TAG_DEFAULT=$(discover_latest_tag "$QUERY_URL" "$YEAR_FILTER" "$RELEASE_TYPE" | grep -E '^[0-9]{4}\.q[1-4]\.[0-9]+' | tail -n1)
        if [[ -z "$LIFERAY_TAG_DEFAULT" ]]; then
          LIFERAY_TAG_DEFAULT=$(discover_latest_tag "$QUERY_URL" "" "$RELEASE_TYPE" | grep -E '^[0-9]{4}\.q[1-4]\.[0-9]+' | tail -n1)
        fi

        if [[ $NON_INTERACTIVE -eq 1 ]]; then
          LIFERAY_TAG="$LIFERAY_TAG_DEFAULT"
        else
          read_config "Enter Liferay Docker Tag" LIFERAY_TAG "$LIFERAY_TAG_DEFAULT"
        fi
      fi

    fi
  fi
fi

# Final Root Resolution
if [[ -z "$LIFERAY_ROOT" ]]; then
  LIFERAY_ROOT_DEFAULT=./${LIFERAY_TAG}
  if [[ $NON_INTERACTIVE -eq 1 ]]; then
    LIFERAY_ROOT="$LIFERAY_ROOT_DEFAULT"
  else
    read_config "Liferay Root" LIFERAY_ROOT "$LIFERAY_ROOT_DEFAULT"
  fi
fi

if ! [[ "$LIFERAY_ROOT" =~ ^(\.\/|\/).+$ ]]; then LIFERAY_ROOT=./$LIFERAY_ROOT; fi

# Resolve Container Name
CONTAINER_NAME=${CONTAINER_ARG:-${META_CONTAINER}}
if [[ -z "$CONTAINER_NAME" ]]; then
  CONTAINER_NAME=$(echo "$LIFERAY_ROOT" | sed -e 's:.*/::' -e 's/[\.]/-/g')
fi

# Ensure volumes and metadata folder
if [[ ! -d "$LIFERAY_ROOT" ]]; then
  info_custom "${Yellow}ℹ Creating ${BYellow}volume ${Yellow}folders"
  mkdir -p "$LIFERAY_ROOT/deploy" && cp ./7.4-common/*activationkeys.xml "$LIFERAY_ROOT/deploy"/ 2>/dev/null
  mkdir -p "$LIFERAY_ROOT/data"
  mkdir -p "$LIFERAY_ROOT/osgi/client-extensions"
  mkdir -p "$LIFERAY_ROOT/osgi/state"
  mkdir -p "$LIFERAY_ROOT/osgi/modules"
  mkdir -p "$LIFERAY_ROOT/files"
  mkdir -p "$LIFERAY_ROOT/scripts"
  mkdir -p "$LIFERAY_ROOT/backups"
  cp ./7.4-common/*.properties "$LIFERAY_ROOT/files"/ 2>/dev/null
fi

DEPLOY_VOLUME=$LIFERAY_ROOT/deploy
DATA_VOLUME=$LIFERAY_ROOT/data
SCRIPT_VOLUME=$LIFERAY_ROOT/scripts
FILES_VOLUME=$LIFERAY_ROOT/files
CX_VOLUME=$LIFERAY_ROOT/osgi/client-extensions
STATE_VOLUME=$LIFERAY_ROOT/osgi/state
MODULES_VOLUME=$LIFERAY_ROOT/osgi/modules
BACKUPS_DIR=$LIFERAY_ROOT/backups

docker container inspect "$CONTAINER_NAME" >/dev/null 2>&1

if [ $? -eq 1 ]; then
  info_custom "${BYELLOW}=== Initializing $CONTAINER_NAME ==="
  if [[ -n "$REMOVE_AFTER_FLAG" ]]; then REMOVE_CONTAINER=Y; elif [[ -n "$KEEP_CONTAINER_FLAG" ]]; then REMOVE_CONTAINER=N; else read_config "Remove container afterwards" REMOVE_CONTAINER Y; fi

  # DB Resolution
  if [[ -n "$DB_KIND" ]]; then 
    LIFERAY_DATABASE="$DB_KIND"
  else
    LIFERAY_DATABASE=${META_DB}
    if [[ -z "$LIFERAY_DATABASE" ]]; then
      if [[ $NON_INTERACTIVE -eq 1 ]]; then 
        LIFERAY_DATABASE="hypersonic"
      else
        read_config "Use Hypersonic database" USE_HYP Y
        if [[ "${USE_HYP:u}" == "Y" ]]; then LIFERAY_DATABASE="hypersonic"; else read_config "Liferay Root - postgresql or mysql" LIFERAY_DATABASE postgresql; fi
      fi
    fi
  fi

  if [[ "${LIFERAY_DATABASE:l}" != "hypersonic" ]]; then
    DATABASE_NAME=${CONTAINER_NAME/-/}
    if [[ "${LIFERAY_DATABASE:l}" == "postgresql" ]]; then
      JDBC_CLASS=org.postgresql.Driver
      JDBC_CONNECTTION=postgresql://host.docker.internal:5432/${DATABASE_NAME}
      if [[ -n "$JDBC_USERNAME_ARG" ]]; then JDBC_USERNAME="$JDBC_USERNAME_ARG"; else read_input "Username" JDBC_USERNAME; fi
      if createdb -h localhost -p 5432 -U ${JDBC_USERNAME} --list | grep -qw "${DATABASE_NAME}" 2>/dev/null; then
        if [[ -n "$RECREATE_DB_FLAG" ]]; then RECREATE_DATABASE=Y; else read_config "Recreate database" RECREATE_DATABASE N; fi
        if [[ "${RECREATE_DATABASE:u}" == "Y" ]]; then
          dropdb -f ${DATABASE_NAME} >/dev/null 2>&1
          createdb -h localhost -p 5432 -U ${JDBC_USERNAME} -O ${JDBC_USERNAME} ${DATABASE_NAME} >/dev/null 2>&1
        fi
      else
        createdb -h localhost -p 5432 -U ${JDBC_USERNAME} -O ${JDBC_USERNAME} ${DATABASE_NAME} >/dev/null 2>&1
      fi
    else
      JDBC_CLASS=com.mysql.cj.jdbc.Driver
      JDBC_CONNECTTION=mysql://host.docker.internal:3306/${DATABASE_NAME}
      if [[ -n "$JDBC_USERNAME_ARG" ]]; then JDBC_USERNAME="$JDBC_USERNAME_ARG"; else read_input "Username" JDBC_USERNAME; fi
      if [[ -n "$JDBC_PASSWORD_ARG" ]]; then JDBC_PASSWORD="$JDBC_PASSWORD_ARG"; else read_password "Password" JDBC_PASSWORD; fi
      if mysql -u "$JDBC_USERNAME" -p"$JDBC_PASSWORD" -e "use ${DATABASE_NAME}" >/dev/null 2>&1; then
        if [[ -n "$RECREATE_DB_FLAG" ]]; then RECREATE_DATABASE=Y; else read_config "Recreate database" RECREATE_DATABASE N; fi
        if [[ "${RECREATE_DATABASE:u}" == "Y" ]]; then
          mysql -u $JDBC_USERNAME -p$JDBC_PASSWORD -e "drop database ${DATABASE_NAME}; create database ${DATABASE_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" >/dev/null 2>&1
        fi
      else
        mysql -u $JDBC_USERNAME -p$JDBC_PASSWORD -e "create database ${DATABASE_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" >/dev/null 2>&1
      fi
    fi
    if ! grep -q "jdbc.default.driverClassName" "${FILES_VOLUME}/portal-ext.properties" 2>/dev/null; then
      { echo -e "\njdbc.default.driverClassName=$JDBC_CLASS"; echo -e "jdbc.default.url=jdbc:$JDBC_CONNECTTION"; echo -e "jdbc.default.username=$JDBC_USERNAME"; [[ -n "$JDBC_PASSWORD" ]] && echo -e "jdbc.default.password=$JDBC_PASSWORD"; } >> "${FILES_VOLUME}"/portal-ext.properties
    fi
  fi

  # Network
  if [[ -n "$HOST_NETWORK_FLAG" ]]; then USE_HOST_NETWORK=True; elif [[ -n "$NO_HOST_NETWORK_FLAG" ]]; then USE_HOST_NETWORK=False; else 
    USE_HOST_NETWORK=${META_HOSTNET:-"False"}
    if [[ "$USE_HOST_NETWORK" == "False" && $NON_INTERACTIVE -eq 0 ]]; then read_config "Use host network" UNET N; if [[ "${UNET:u}" == "Y" ]]; then USE_HOST_NETWORK=True; fi; fi
  fi

  # Port
  LOCAL_PORT=${PORT_ARG:-${META_PORT:-8080}}
  if [[ "$USE_HOST_NETWORK" != "True" && $NON_INTERACTIVE -eq 0 && -z "$PORT_ARG" && -z "$META_PORT" ]]; then read_config "Local Port" LOCAL_PORT 8080; fi

  # Zip64
  DZ64=False
  if [[ -n "$DISABLE_ZIP64_FLAG_EXPL" ]]; then DZ64=True; fi

  if [[ "$DZ64" == "True" ]]; then DISABLE_ZIP64_FLAG="-e LIFERAY_JVM_OPTS=-Djdk.util.zip.disableZip64ExtraFieldValidation=true"; fi
  if [[ "$USE_HOST_NETWORK" == "True" ]]; then NETWORK_ARGS="--network=host"; else NETWORK_ARGS="-p ${LOCAL_PORT}:8080"; fi

  LIFRAY_IMAGE_TAG=$IMAGE_NAME:$LIFERAY_TAG
  info_custom "${Yellow}ℹ Pulling ${BYellow}$LIFRAY_IMAGE_TAG"
  docker pull "$LIFRAY_IMAGE_TAG"
  docker create -it ${NETWORK_ARGS} --name "${CONTAINER_NAME}" ${DISABLE_ZIP64_FLAG} -v "${FILES_VOLUME}:/mnt/liferay/files" -v "${SCRIPT_VOLUME}:/mnt/liferay/scripts" -v "${STATE_VOLUME}:/opt/liferay/osgi/state" -v "${MODULES_VOLUME}:/opt/liferay/modules" -v "${DATA_VOLUME}:/opt/liferay/data" -v "${DEPLOY_VOLUME}:/mnt/liferay/deploy" -v "${CX_VOLUME}:/opt/liferay/osgi/client-extensions" "$LIFRAY_IMAGE_TAG"

  # Save Metadata
  write_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "tag" "$LIFERAY_TAG"
  write_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "port" "$LOCAL_PORT"
  write_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "db_type" "$LIFERAY_DATABASE"
  write_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "container_name" "$CONTAINER_NAME"
  write_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "host_network" "$USE_HOST_NETWORK"
  write_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "last_run" "$(date -Iseconds)"

  docker start -i -a "${CONTAINER_NAME}"
  if [[ "${REMOVE_CONTAINER:u}" == "Y" ]]; then info "Deleting $CONTAINER_NAME"; docker rm --force "$CONTAINER_NAME" >/dev/null 2>&1; else info "Stopping $CONTAINER_NAME"; docker stop "$CONTAINER_NAME" >/dev/null 2>&1; fi
else
  info_custom "${BYELLOW}=== Resuming $CONTAINER_NAME ==="
  if [[ -n "$REMOVE_AFTER_FLAG" ]]; then REMOVE_CONTAINER=Y; elif [[ -n "$KEEP_CONTAINER_FLAG" ]]; then REMOVE_CONTAINER=N; else read_config "Remove container afterwards" REMOVE_CONTAINER N; fi
  if [[ -n "$DELETE_STATE_FLAG" ]]; then RS=Y; else read_config "Delete OSGi state folder" RS Y; fi
  if [[ "${RS:u}" == "Y" ]]; then info "Clearing OSGi state..."; rm -R "$STATE_VOLUME" 2>/dev/null; mkdir -p "$STATE_VOLUME"; fi

  # Update last_run
  write_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "last_run" "$(date -Iseconds)"

  docker start -i -a "${CONTAINER_NAME}"
  if [[ "${REMOVE_CONTAINER:u}" == "Y" ]]; then info "Deleting $CONTAINER_NAME"; docker rm --force "$CONTAINER_NAME" >/dev/null 2>&1; else info "Stopping $CONTAINER_NAME"; docker stop "$CONTAINER_NAME" >/dev/null 2>&1; fi
fi
