#!/bin/zsh
# This script is strictly compatible with Zsh only.
# It utilizes Zsh-specific features like array expansion flags ${(z)var},
# native path expansion ${0:A:h}, and specialized globbing control.
setopt nullglob

Color_Off='\033[0m'
Green='\033[0;32m'
Yellow='\033[0;33m'
White='\033[0;37m'
BYELLOW='\033[1;33m'
Red='\033[0;31m'
BRed='\033[1;31m'
Cyan='\033[0;36m'

info() { [[ -n $* ]] && echo -e "${Yellow}ℹ $1${Color_Off}"; }
info_custom() { [[ -n $* ]] && echo -e "$1${Color_Off}"; }
error() { echo -e "${BRed}❌ Error:${Color_Off} $*" 1>&2; }
_die() {
	error "$*"
	exit 1
}
read_config() {
	if [[ "$NON_INTERACTIVE" == 1 ]]; then
		typeset -g "$2"="$3"
		return
	fi
	if [[ -n $* ]]; then
		local ANSWER
		echo -n -e "${White}❓ $1 [${Green}$3${White}]: ${Color_Off}"
		read -r ANSWER
		typeset -g "$2"="${ANSWER:-$3}"
	fi
}
read_input() {
	if [[ "$NON_INTERACTIVE" == 1 ]]; then
		typeset -g "$2"="$3"
		return
	fi
	if [[ -n $* ]]; then
		local ANSWER
		echo -n -e "${White}❓ $1: ${Color_Off}"
		read -r ANSWER
		typeset -g "$2"="${ANSWER}"
	fi
}
read_password() {
	if [[ "$NON_INTERACTIVE" == 1 ]]; then
		typeset -g "$2"="$3"
		return
	fi
	if [[ -n $* ]]; then
		local ANSWER
		echo -n -e "${White}❓ $1: ${Color_Off}"
		read -r rs ANSWER
		echo -e ""
		typeset -g "$2"="${ANSWER}"
	fi
}

if ! docker info >/dev/null 2>&1; then
	_die "Docker is not running or not accessible. Please start Docker and try again."
fi

export DOCKER_CLI_HINTS=false
SCRIPT_DIR="${0:A:h}"
IMAGE_NAME=liferay/dxp
PROJECT_META_FILE=".liferay-docker.meta"

NON_INTERACTIVE=0
QUIET=0
VERBOSE=0
RUN_SELECT=0
REFRESH_CACHE=0
ROOT_ARG=""
TAG_ARG=""
CONTAINER_ARG=""
RELEASE_TYPE_ARG=""
DB_KIND=""
JDBC_USERNAME_ARG=""
JDBC_PASSWORD_ARG=""
RECREATE_DB_FLAG=""
HOST_NETWORK_FLAG=""
NO_HOST_NETWORK_FLAG=""
HOST_NAME_ARG=""
ES_PORT_ARG=""
DISABLE_ZIP64_FLAG_EXPL=""
PORT_ARG=""
REMOVE_AFTER_FLAG=""
KEEP_CONTAINER_FLAG=""
DELETE_STATE_FLAG=""
SSL_FLAG=""
NO_SSL_FLAG=""
FOLLOW_FLAG=0

read_meta() {
	local file="$1"
	local key="$2"
	if [[ -f "$file" ]]; then
		grep "^$key=" "$file" | cut -d'=' -f2-
	fi
}

write_meta() {
	local file="$1"
	local tmpfile="${file}.tmp"
	# Read existing if present to merge
	if [[ -f "$file" ]]; then
		cp "$file" "$tmpfile"
	else
		echo "# Generated by Liferay Docker Manager ($(date -Iseconds))" >"$tmpfile"
	fi

	# For each pair of key=val in subsequent args
	shift
	while [[ $# -gt 0 ]]; do
		local key="$1"
		local val="$2"
		shift 2
		if grep -q "^$key=" "$tmpfile"; then
			sed -i "" "s|^$key=.*|$key=$val|" "$tmpfile"
		else
			echo "$key=$val" >>"$tmpfile"
		fi
	done
	mv "$tmpfile" "$file"
}

wait_for_container_stop() {
	local container="$1"
	local timeout=30
	local start=$(date +%s)
	while (($(date +%s) - start < timeout)); do
		local status=$(docker inspect -f '{{.State.Status}} {{.State.Running}}' "$container" 2>/dev/null)
		[[ -z "$status" ]] && return 0 # No longer exists
		local parts=(${(z)status})
		if [[ "${parts[1]}" == "exited" && "${parts[2]}" == "false" ]]; then
			return 0
		fi
		sleep 1
	done
	return 1
}

update_portal_ext() {
	local file="$1"
	shift
	[[ ! -f "$file" ]] && touch "$file"
	while [[ $# -gt 0 ]]; do
		local key="$1"
		local val="$2"
		shift 2
		if grep -qE "^\s*${key}\s*=" "$file"; then
			sed -i "" "s|^\s*${key}\s*=.*|${key}=${val}|" "$file"
		else
			echo "${key}=${val}" >>"$file"
		fi
	done
}

check_port_available() {
	local port="$1"
	local ip="${2:-127.0.0.1}"
	python3 -c "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.settimeout(0.5); s.bind(('$ip', $port)); s.close()" 2>/dev/null
}

discover_latest_tag() {
	local query_url="$1"
	local year_filter="$2"
	local release_type="$3"
	local cache_file="$HOME/.liferay_docker_cache.json"
	local cache_key="${query_url}_${release_type}_${year_filter}"

	if [[ $REFRESH_CACHE -ne 1 && -f "$cache_file" ]]; then
		local entry=$(python3 -c "
import json, os, time
try:
    with open('$cache_file', 'r') as f:
        cache = json.load(f)
        if '$cache_key' in cache:
            entry = cache['$cache_key']
            if time.time() - entry.get('timestamp', 0) < 86400:
                print(entry['tag'])
except: pass
" 2>/dev/null)
		if [[ -n "$entry" ]]; then
			echo "$entry"
			return
		fi
	fi

	echo "Initial tag discovery (this may take a few seconds)..." >&2
	local start_time=$(date +%s)
	local url="$query_url"
	local tags=()
	local page=0

	while [[ -n "$url" ]]; do
		((page++))
		printf "\rFetching page $page..." >&2
		local json=$(curl -s "$url") || break

		local names=($(echo "$json" | jq -r '.results[].name'))
		for name in "${names[@]}"; do
			[[ -z "$name" ]] && continue
			[[ -n "$year_filter" && "$name" != ${year_filter}* ]] && continue
			[[ "$name" =~ ^[0-9]{4}\.q[1-4]\.[0-9]+(-u[0-9]+|-lts)?$ ]] && tags+=("$name")
		done
		url=$(echo "$json" | jq -r '.next // empty')
	done

	local duration=$(($(date +%s) - start_time))
	printf "\nFetched $page pages in ${duration}s\n" >&2

	local latest_tag=""
	if ((${#tags[@]} > 0)); then
		latest_tag=$(printf '%s\n' "${tags[@]}" | sort -V | tail -n1)
	fi

	# Save to Cache (using python for easy JSON handling)
	python3 -c "
import json, time, os
cache_file = os.path.expanduser('~/.liferay_docker_cache.json')
try:
    with open(cache_file, 'r') as f: cache = json.load(f)
except: cache = {}
cache['$cache_key'] = {'tag': '$latest_tag', 'timestamp': time.time()}
with open(cache_file, 'w') as f: json.dump(cache, f)
" 2>/dev/null

	echo "$latest_tag"
}

setup_infrastructure() {
	local ip="$1"
	local port="$2"
	local root="$3"
	# 1. Silent Network Creation
	docker network inspect liferay-proxy-net >/dev/null 2>&1 || docker network create liferay-proxy-net >/dev/null 2>&1

	# 2. macOS Socat Bridge (Cross-platform reliability fix)
	local DOCKER_ENDPOINT="unix:///var/run/docker.sock"
	local SOCKET_MOUNT="-v /var/run/docker.sock:/var/run/docker.sock:ro"

	if [[ "$(uname)" == "Darwin" ]]; then
		if ! docker ps -q -f name=docker-socket-proxy | grep -q .; then
			local REAL_HOME=$(eval echo "~${SUDO_USER:-$USER}")
			local docker_sock="$REAL_HOME/.docker/run/docker.sock"
			[[ ! -S "$docker_sock" ]] && docker_sock="/var/run/docker.sock"

			info "Starting macOS Docker socket bridge (socat)..."
			docker run -d --rm --name docker-socket-proxy --network liferay-proxy-net -v "$HOME/.liferay_docker_certs:/etc/traefik/certs:ro" -v "$docker_sock:/var/run/docker.sock:ro" alpine/socat TCP-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock >/dev/null 2>&1
		fi
		DOCKER_ENDPOINT="tcp://docker-socket-proxy:2375"
		SOCKET_MOUNT="" # macOS uses TCP bridge, no direct mount needed for Traefik
	fi

	# 3. Singleton Proxy Check
	if docker ps -q -f name=liferay-proxy-global | grep -q .; then
		return 0
	fi

	info "Starting global Traefik SSL proxy..."
	docker rm -f liferay-proxy-global >/dev/null 2>&1
	docker pull traefik:v3.3 >/dev/null
	docker run -d --rm --name liferay-proxy-global --network liferay-proxy-net -e DOCKER_API_VERSION=1.44 -p "${ip}:${port}:443" ${SOCKET_MOUNT} -v "${root}/.certs:/etc/traefik/certs:ro" traefik:v3.3 --providers.docker=true --providers.docker.endpoint="$DOCKER_ENDPOINT" --providers.docker.exposedbydefault=false --entrypoints.websecure.address=:443 --providers.file.directory=/etc/traefik/certs --providers.file.watch=true >/dev/null
}

normalize_jdbc() {
	local url="$1"
	[[ -z "$url" ]] && return
	python3 -c "
import re
url = '$url'
pattern = r'^jdbc:(postgresql|mysql|mariadb)://([^:/]+)(?::(\d+))?/([^/?]+)'
match = re.match(pattern, url)
if match:
    driver, host, port, db_name = match.groups()
    if host in ['localhost', 'host.docker.internal']: host = '127.0.0.1'
    if not port: port = '5432' if driver == 'postgresql' else '3306'
    print(f'{driver}|{host}|{port}|{db_name}')
" 2>/dev/null
}

print_macos_alias_advice() {
	local ip="$1"
	if [[ "$(uname)" == "Darwin" ]]; then
		echo -e "\n${BRed}OSX DETECTED:${Color_Off} You must alias this IP to your loopback interface."
		echo -e "Run the following command in your terminal:"
		echo -e "${Cyan}sudo ifconfig lo0 alias $ip up${Color_Off}\n"
	else
		echo -e "\nEnsure your network interface is configured to handle $ip."
	fi
}

while [[ $# -gt 0 ]]; do
	case "$1" in
	--select) RUN_SELECT=1 ;;
	--refresh) REFRESH_CACHE=1 ;;
	-r | --root)
		shift
		[[ -z "$1" ]] && _die "--root requires a path"
		ROOT_ARG="$1"
		;;
	-t | --tag)
		shift
		[[ -z "$1" ]] && _die "--tag requires a value"
		TAG_ARG="$1"
		;;
	-c | --container)
		shift
		[[ -z "$1" ]] && _die "--container requires a name"
		CONTAINER_ARG="$1"
		;;
	--release-type)
		shift
		[[ -z "$1" ]] && _die "--release-type requires any|u|lts|qr"
		case "${1:l}" in any | u | lts | qr) RELEASE_TYPE_ARG="${1:l}" ;; *) _die "--release-type must be any|u|lts|qr" ;; esac
		;;
	--non-interactive) NON_INTERACTIVE=1 ;;
	--db)
		shift
		[[ -z "$1" ]] && _die "--db requires postgresql|mysql|hypersonic"
		case "${1:l}" in postgresql | mysql | hypersonic) DB_KIND="${1:l}" ;; *) _die "--db must be postgresql|mysql|hypersonic" ;; esac
		;;
	--hypersonic) DB_KIND="hypersonic" ;;
	--jdbc-username)
		shift
		[[ -z "$1" ]] && _die "--jdbc-username requires a value"
		JDBC_USERNAME_ARG="$1"
		;;
	--jdbc-password)
		shift
		[[ -z "$1" ]] && _die "--jdbc-password requires a value"
		JDBC_PASSWORD_ARG="$1"
		;;
	--recreate-db) RECREATE_DB_FLAG=1 ;;
	--host-network) HOST_NETWORK_FLAG=1 ;;
	--no-host-network) NO_HOST_NETWORK_FLAG=1 ;;
	--host-name)
		shift
		[[ -z "$1" ]] && _die "--host-name requires a value"
		HOST_NAME_ARG="$1"
		;;
	--es-port)
		shift
		[[ -z "$1" || "$1" != <-> ]] && _die "--es-port requires a number"
		ES_PORT_ARG="$1"
		;;
	--disable-zip64) DISABLE_ZIP64_FLAG_EXPL=1 ;;
	-p | --port)
		shift
		[[ -z "$1" || "$1" != <-> ]] && _die "--port requires a number"
		PORT_ARG="$1"
		;;
	--remove-after) REMOVE_AFTER_FLAG=1 ;;
	--keep-container) KEEP_CONTAINER_FLAG=1 ;;
	--delete-state) DELETE_STATE_FLAG=1 ;;
	--ssl) SSL_FLAG=1 ;;
	--no-ssl) NO_SSL_FLAG=1 ;;
	-f | --follow) FOLLOW_FLAG=1 ;;
	--quiet) QUIET=1 ;;
	--verbose) VERBOSE=1 ;;
	-h | --help)
		echo "Usage: $0 [options]"
		echo ""
		echo "Core paths and image:"
		echo "      --select                  Browse and select managed DXP folders"
		echo "      --refresh                 Force refresh of Docker Hub tag cache"
		echo "  -t, --tag <tag>               Liferay Docker image tag. Default: latest tag for chosen release type"
		echo "  -r, --root <path>             Project root. Default: ./<tag>"
		echo "  -c, --container <name>        Container name. Default: basename(<root>) with dots replaced by dashes"
		echo "      --release-type any|u|lts|qr  Tag discovery mode. Default: any"
		echo ""
		echo "Database selection:"
		echo "      --db postgresql|mysql|hypersonic  Database choice. Default: prompt; non-interactive defaults to hypersonic unless JDBC opts provided"
		echo "      --jdbc-username <name>    Username for external DB"
		echo "      --jdbc-password <pass>    Password for external DB"
		echo "      --recreate-db             Drop and recreate the target database if it exists"
		echo ""
		echo "Runtime behavior:"
		echo "  -p, --port <8080>             Local HTTP port mapping. Default: 8080"
		echo "      --host-network|--no-host-network  Use or avoid host networking. Default: disabled"
		echo "      --host-name <hostname>    Virtual hostname for the instance. Default: localhost"
		echo "      --es-port <port>          Elasticsearch sidecar HTTP port. Default: 9200"
		echo "      --disable-zip64           Disable Zip64 extra field validation. Default: enabled"
		echo "  -f, --follow                  Start container and follow logs (attach). Default: background"
		echo "      --remove-after|--keep-container   Remove container after run or keep it. Default: keep when created, background start when kept"
		echo "      --delete-state             When container already exists, delete osgi/state before starting"
		echo "      --non-interactive         Do not prompt; apply defaults and provided flags"
		echo "      --quiet | --verbose       Adjust logging"
		exit 0
		;;
	*) _die "Unknown option: $1" ;;
	esac
	shift
done

if [[ $RUN_SELECT -eq 1 ]]; then
	folders=()
	versions=()
	for d in */; do
		d=${d%/}
		if [[ -d "$d/files" || -d "$d/deploy" || -f "$d/$PROJECT_META_FILE" ]]; then
			if [[ "$d" != "common" && "$d" != .* ]]; then
				folders+=("$d")
				ver=$(read_meta "$d/$PROJECT_META_FILE" "tag")
				versions+=("${ver:-unknown}")
			fi
		fi
	done

	info_custom "${BYELLOW}=== Available DXP Folders ==="
	if ((${#folders[@]} > 0)); then
		for i in {1..${#folders[@]}}; do
			info_custom "${White}[$i] ${folders[$i]} [${Cyan}${versions[$i]}${White}]"
		done
	fi
	info_custom "${White}[$((${#folders[@]} + 1))] Create New..."

	read_config "Select folder index" CHOICE_IDX 1
	if [[ "$CHOICE_IDX" -gt 0 && "$CHOICE_IDX" -le ${#folders[@]} ]]; then
		LIFERAY_ROOT="${folders[$CHOICE_IDX]}"
		ROOT_ARG="$LIFERAY_ROOT"
	elif [[ "$CHOICE_IDX" -eq $((${#folders[@]} + 1)) ]]; then
		ROOT_ARG=""
		TAG_ARG=""
	else
		_die "Invalid selection."
	fi
fi

if [[ -n "$ROOT_ARG" ]]; then
	LIFERAY_ROOT="$ROOT_ARG"
else
	if [[ -n "$TAG_ARG" ]]; then
		LIFERAY_ROOT_DEFAULT=./${TAG_ARG}
	else
		LIFERAY_ROOT_DEFAULT=""
	fi
fi

if [[ -n "$LIFERAY_ROOT" && -d "$LIFERAY_ROOT" ]]; then
	META_TAG=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "tag")
	META_PORT=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "port")
	META_DB=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "db_type")
	META_CONTAINER=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "container_name")
	META_HOSTNET=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "host_network")
	META_HOSTNAME=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "host_name")
	META_ES_PORT=$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "es_port")
fi

REQUESTED_PORT=${PORT_ARG:-${META_PORT:-8080}}
REQUESTED_HOSTNAME=${HOST_NAME_ARG:-${META_HOSTNAME:-localhost}}
REQUESTED_ES_PORT=${ES_PORT_ARG:-${META_ES_PORT:-9200}}

if [[ "$REQUESTED_HOSTNAME" == "localhost" ]]; then
	REQUESTED_IP="127.0.0.1"
else
	REQUESTED_IP=$(python3 -c "import socket; print(socket.gethostbyname('$REQUESTED_HOSTNAME'))" 2>/dev/null)
	[[ -z "$REQUESTED_IP" ]] && REQUESTED_IP="127.0.0.1"
fi

LOCAL_PORT=$REQUESTED_PORT
HOST_NAME=$REQUESTED_HOSTNAME
ES_PORT=$REQUESTED_ES_PORT
RESOLVED_IP=$REQUESTED_IP

# SSL Pre-flight
USE_SSL=0
if [[ -n "$SSL_FLAG" ]]; then USE_SSL=1; elif [[ -n "$NO_SSL_FLAG" ]]; then USE_SSL=0; else
	if [[ "$HOST_NAME" != "localhost" && -n "$HOST_NAME" ]]; then USE_SSL=1; fi
fi

SSL_PORT=443
if [[ $USE_SSL -eq 1 ]]; then
	if [[ "$USE_HOST_NETWORK" == "True" ]]; then
		_die "SSL with Traefik is not supported in --host-network mode."
	fi

	if ! check_port_available 443 "$RESOLVED_IP"; then
		if ! docker ps -q -f name=liferay-proxy-global | grep -q .; then
			error "Host port 443 is blocked on $RESOLVED_IP."
			info "HINT: To use the standard HTTPS port, run this script with sudo."
			if [[ $NON_INTERACTIVE -eq 0 ]]; then
				read_config "Would you like to continue using port 8443 instead?" CONT_8443 Y
				if [[ "${CONT_8443:u}" == "Y" ]]; then
					if ! check_port_available 8443 "$RESOLVED_IP"; then
						_die "Host port 8443 is also in use on $RESOLVED_IP. Aborting SSL setup."
					fi
					SSL_PORT=8443
				else
					exit 0
				fi
			else
				_die "Port 443 unavailable in non-interactive mode. Aborting."
			fi
		fi
	fi
fi

if [[ "$HOST_NAME" != "localhost" ]]; then
	info "Verifying resolution for '$HOST_NAME'..."
	if [[ "$RESOLVED_IP" != 127.* && "$RESOLVED_IP" != "::1" && "$RESOLVED_IP" != "0:0:0:0:0:0:0:1" ]]; then
		error "Hostname '$HOST_NAME' resolves to $RESOLVED_IP, which is not a local loopback address."
		echo -e "\n${BRed}IMPORTANT:${Color_Off} You must map '$HOST_NAME' to a loopback address (e.g. 127.0.0.1) in your OS hosts file."
		echo -e "Add the following line:\n${Green}127.0.0.1  $HOST_NAME${Color_Off}"
		if [[ $NON_INTERACTIVE -eq 1 ]]; then exit 1; fi
		read_config "Continue anyway?" CONT_HOST N
		[[ "${CONT_HOST:u}" != "Y" ]] && exit 1
	else
		if ! check_port_available 0 "$RESOLVED_IP"; then
			error "IP address $RESOLVED_IP is not available for binding on this host."
			print_macos_alias_advice "$RESOLVED_IP"
			if [[ $NON_INTERACTIVE -eq 1 ]]; then exit 1; fi
			read_config "Continue anyway?" CONT_BIND N
			[[ "${CONT_BIND:u}" != "Y" ]] && exit 1
		fi
	fi
fi

# Collision Scan & Port Auto-Increment
PORT_ASSIGNED=0
while [[ $PORT_ASSIGNED -eq 0 ]]; do
	COLLISION_FOUND=0
	for d in */; do
		d=${d%/}
		[[ "$d" == "common" || "$d" == .* || "./$d" == "$LIFERAY_ROOT" ]] && continue
		M_FILE="$d/$PROJECT_META_FILE"
		[[ ! -f "$M_FILE" ]] && continue

		M_CONT=$(read_meta "$M_FILE" "container_name")
		M_PORT=$(read_meta "$M_FILE" "port")
		M_HOST=$(read_meta "$M_FILE" "host_name")

		M_IP=$(python3 -c "import socket; print(socket.gethostbyname('${M_HOST:-localhost}'))" 2>/dev/null)
		[[ -z "$M_IP" ]] && M_IP="127.0.0.1"

		# Port Conflict Check
		if docker ps --filter "name=^${M_CONT}$" --format "{{.Names}}" | grep -q "^${M_CONT}$"; then
			if [[ "$LOCAL_PORT" == "$M_PORT" && "$RESOLVED_IP" == "$M_IP" ]]; then
				LOCAL_PORT=$(($LOCAL_PORT + 1))
				COLLISION_FOUND=1
				break
			fi
		fi
	done

	if [[ $COLLISION_FOUND -eq 0 ]]; then
		if ! check_port_available "$LOCAL_PORT" "$RESOLVED_IP"; then
			LOCAL_PORT=$(($LOCAL_PORT + 1))
			continue
		fi
		PORT_ASSIGNED=1
	fi
done

if [[ -n "$TAG_ARG" ]]; then
	LIFERAY_TAG="$TAG_ARG"
else
	LIFERAY_TAG=${META_TAG}
	if [[ -z "$LIFERAY_TAG" ]]; then
		API_BASE='https://hub.docker.com/v2/repositories/liferay/dxp/tags?page_size=200&ordering=name'
		[[ $NON_INTERACTIVE -eq 1 ]] && RELEASE_TYPE=any || read_config "Release type (any|u|lts|qr) or Enter Tag" RELEASE_TYPE any
		if [[ "$RELEASE_TYPE" =~ ^[0-9]{4}\.q[1-4]\.[0-9]+(-u[0-9]+|-lts)?$ ]]; then
			LIFERAY_TAG="$RELEASE_TYPE"
		else
			case "${RELEASE_TYPE:l}" in lts) QUERY_URL="$API_BASE&name=-lts" ;; u) QUERY_URL="$API_BASE&name=-u" ;; *) QUERY_URL="$API_BASE" ;; esac
			YEAR_FILTER=$(date +%Y)
			LIFERAY_TAG_DEFAULT=$(discover_latest_tag "$QUERY_URL" "$YEAR_FILTER" "$RELEASE_TYPE" | grep -E '^[0-9]{4}\.q[1-4]\.[0-9]+' | tail -n1)
			[[ -z "$LIFERAY_TAG_DEFAULT" ]] && LIFERAY_TAG_DEFAULT=$(discover_latest_tag "$QUERY_URL" "" "$RELEASE_TYPE" | grep -E '^[0-9]{4}\.q[1-4]\.[0-9]+' | tail -n1)
			[[ $NON_INTERACTIVE -eq 1 ]] && LIFERAY_TAG="$LIFERAY_TAG_DEFAULT" || read_config "Enter Liferay Docker Tag" LIFERAY_TAG "$LIFERAY_TAG_DEFAULT"
		fi
	fi
fi

[[ -z "$LIFERAY_ROOT" ]] && { [[ $NON_INTERACTIVE -eq 1 ]] && LIFERAY_ROOT="./$LIFERAY_TAG" || read_config "Liferay Root" LIFERAY_ROOT "./$LIFERAY_TAG"; }
[[ ! "$LIFERAY_ROOT" =~ ^(\.\/|\/).+$ ]] && LIFERAY_ROOT=./$LIFERAY_ROOT
# Normalize path to absolute
LIFERAY_ROOT=$(cd "$LIFERAY_ROOT" 2>/dev/null && pwd || echo "$LIFERAY_ROOT")
CONTAINER_NAME=${CONTAINER_ARG:-${META_CONTAINER:-$(echo "$LIFERAY_ROOT" | sed -e 's:.*/::' -e 's/[\.]/-/g')}}

if [[ ! -d "$LIFERAY_ROOT" ]]; then
	info_custom "${Yellow}ℹ Creating ${BYellow}volume ${Yellow}folders"
	mkdir -p "$LIFERAY_ROOT"/{deploy,data,osgi/client-extensions,osgi/state,osgi/modules,files,scripts,backups}
	for f in "$SCRIPT_DIR"/common/*activationkeys.xml; do cp "$f" "$LIFERAY_ROOT/deploy"/ 2>/dev/null; done
	for f in "$SCRIPT_DIR"/common/*.properties; do cp "$f" "$LIFERAY_ROOT/files"/ 2>/dev/null; done
fi

FILES_VOLUME="$LIFERAY_ROOT/files"
STATE_VOLUME="$LIFERAY_ROOT/osgi/state"

FORCE_INIT=0
if docker container inspect "$CONTAINER_NAME" >/dev/null 2>&1; then
	if [[ $NON_INTERACTIVE -eq 0 ]]; then
		read_config "Container '$CONTAINER_NAME' already exists. Would you like to remove it and re-initialize?" REMOVE_EXISTING N
		if [[ "${REMOVE_EXISTING:u}" == "Y" ]]; then
			info "Removing existing container $CONTAINER_NAME..."
			docker rm -f "$CONTAINER_NAME" >/dev/null
			FORCE_INIT=1
		fi
	fi
else
	FORCE_INIT=1
fi

if [[ $FORCE_INIT -eq 1 ]]; then
	info_custom "${BYELLOW}=== Initializing $CONTAINER_NAME ==="

	# Smart 'Remove' Logic
	REMOVE_CONTAINER=N
	[[ -n "$REMOVE_AFTER_FLAG" ]] && REMOVE_CONTAINER=Y
	if [[ "$REMOVE_CONTAINER" == "N" && $FOLLOW_FLAG -eq 1 && $NON_INTERACTIVE -eq 0 ]]; then
		read_config "Remove container afterwards" REM_C N
		[[ "${REM_C:u}" == "Y" ]] && REMOVE_CONTAINER=Y
	fi

	if [[ -n "$DB_KIND" ]]; then LIFERAY_DATABASE="$DB_KIND"; else
		LIFERAY_DATABASE=${META_DB:-"hypersonic"}
		if [[ $NON_INTERACTIVE -eq 0 && -z "$DB_KIND" ]]; then
			read_config "Use Hypersonic database" USE_HYP Y
			[[ "${USE_HYP:u}" == "Y" ]] && LIFERAY_DATABASE="hypersonic" || read_config "Liferay Root - postgresql or mysql" LIFERAY_DATABASE postgresql
		fi
	fi

	if [[ "${LIFERAY_DATABASE:l}" != "hypersonic" ]]; then
		DATABASE_NAME=${CONTAINER_NAME/-/}
		if [[ "${LIFERAY_DATABASE:l}" == "postgresql" ]]; then
			JDBC_CLASS=org.postgresql.Driver
			JDBC_URL=jdbc:postgresql://host.docker.internal:5432/${DATABASE_NAME}
			[[ -n "$JDBC_USERNAME_ARG" ]] && JDBC_USERNAME="$JDBC_USERNAME_ARG" || read_input "Username" JDBC_USERNAME
			if createdb -h localhost -p 5432 -U ${JDBC_USERNAME} --list | grep -qw "${DATABASE_NAME}" 2>/dev/null; then
				[[ -n "$RECREATE_DB_FLAG" ]] && REC=Y || read_config "Recreate database" REC N
				if [[ "${REC:u}" == "Y" ]]; then
					dropdb -f ${DATABASE_NAME} 2>/dev/null
					createdb -h localhost -p 5432 -U ${JDBC_USERNAME} -O ${JDBC_USERNAME} ${DATABASE_NAME} 2>/dev/null
				fi
			else createdb -h localhost -p 5432 -U ${JDBC_USERNAME} -O ${JDBC_USERNAME} ${DATABASE_NAME} 2>/dev/null; fi
		else
			JDBC_CLASS=com.mysql.cj.jdbc.Driver
			JDBC_URL=jdbc:mysql://host.docker.internal:3306/${DATABASE_NAME}
			[[ -n "$JDBC_USERNAME_ARG" ]] && JDBC_USERNAME="$JDBC_USERNAME_ARG" || read_input "Username" JDBC_USERNAME
			[[ -n "$JDBC_PASSWORD_ARG" ]] && JDBC_PASSWORD="$JDBC_PASSWORD_ARG" || read_password "Password" JDBC_PASSWORD
			if mysql -u "$JDBC_USERNAME" -p"$JDBC_PASSWORD" -e "use ${DATABASE_NAME}" 2>/dev/null; then
				[[ -n "$RECREATE_DB_FLAG" ]] && REC=Y || read_config "Recreate database" REC N
				if [[ "${REC:u}" == "Y" ]]; then mysql -u $JDBC_USERNAME -p$JDBC_PASSWORD -e "drop database ${DATABASE_NAME}; create database ${DATABASE_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>/dev/null; fi
			else mysql -u $JDBC_USERNAME -p$JDBC_PASSWORD -e "create database ${DATABASE_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>/dev/null; fi
		fi
		update_portal_ext "${FILES_VOLUME}/portal-ext.properties" "jdbc.default.driverClassName" "$JDBC_CLASS" "jdbc.default.url" "$JDBC_URL" "jdbc.default.username" "$JDBC_USERNAME"
		[[ -n "$JDBC_PASSWORD" ]] && update_portal_ext "${FILES_VOLUME}/portal-ext.properties" "jdbc.default.password" "$JDBC_PASSWORD"
	fi

	[[ -n "$HOST_NETWORK_FLAG" ]] && USE_HOST_NETWORK=True || { [[ -n "$NO_HOST_NETWORK_FLAG" ]] && USE_HOST_NETWORK=False || {
		USE_HOST_NETWORK=${META_HOSTNET:-"False"}
		[[ "$USE_HOST_NETWORK" == "False" && $NON_INTERACTIVE -eq 0 ]] && {
			read_config "Use host network" UNET N
			[[ "${UNET:u}" == "Y" ]] && USE_HOST_NETWORK=True
		}
	}; }

	# Network & Traefik Labels
	TRAEFIK_LABELS=()
	NETWORK_ARGS=("-p" "${RESOLVED_IP}:${LOCAL_PORT}:8080")
	if [[ $USE_SSL -eq 1 ]]; then
		TRAEFIK_LABELS=(
			"--label" "traefik.enable=true"
			"--label" "traefik.http.routers.${CONTAINER_NAME}.rule=Host(\`${HOST_NAME}\`)"
			"--label" "traefik.http.routers.${CONTAINER_NAME}.entrypoints=websecure"
			"--label" "traefik.http.routers.${CONTAINER_NAME}.tls=true"
			"--label" "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=8080"
			"--label" "traefik.docker.network=liferay-proxy-net"
		)
		# Use shared bridge for SSL
		NETWORK_ARGS=("--network=liferay-proxy-net" "${NETWORK_ARGS[@]}")
	elif [[ "$USE_HOST_NETWORK" == "True" ]]; then
		NETWORK_ARGS=("--network=host")
	fi

	# ES Port logic: Skip prompt and handle busy port gracefully
	ES_PORT=${ES_PORT_ARG:-${META_ES_PORT:-9200}}
	if check_port_available "$ES_PORT" "$RESOLVED_IP"; then
		NETWORK_ARGS+=("-p" "${RESOLVED_IP}:${ES_PORT}:9200")
	else
		info "Note: Host port $ES_PORT is busy. ES sidecar is active internally but not exposed."
	fi

	JVM_OPTS=""
	[[ -n "$DISABLE_ZIP64_FLAG_EXPL" ]] && JVM_OPTS="-Djdk.util.zip.disableZip64ExtraFieldValidation=true"
	if [[ "$HOST_NAME" != "localhost" ]]; then
		COOKIE_ID="LFR_SESSION_ID_$(echo "$HOST_NAME" | sed 's/[\.-]/_/g')"
		JVM_OPTS="${JVM_OPTS} -Dorg.apache.catalina.SESSION_COOKIE_NAME=${COOKIE_ID}"
		update_portal_ext "${FILES_VOLUME}/portal-ext.properties" "session.cookie.domain" "$HOST_NAME" "session.cookie.use.full.hostname" "true" "virtual.hosts.valid.hosts" "localhost,127.0.0.1,[::1],${HOST_NAME},${RESOLVED_IP}"
	fi
	[[ "$ES_PORT" != "9200" ]] && update_portal_ext "${FILES_VOLUME}/portal-ext.properties" "module.framework.properties.com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.sidecarHttpPort" "$ES_PORT" "module.framework.properties.com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.transportTcpPort" "$(($ES_PORT + 100))"

	# SSL Setup
	if [[ $USE_SSL -eq 1 ]]; then
		if ! command -v mkcert &>/dev/null; then
			error "mkcert is not installed. SSL support will be skipped."
			USE_SSL=0
		else
			CERT_DIR="$HOME/.liferay_docker_certs"
			mkdir -p "$CERT_DIR"
			if [[ ! -f "$CERT_DIR/$HOST_NAME.pem" ]]; then
				info "Generating SSL certificate for $HOST_NAME..."
				mkcert -cert-file "$CERT_DIR/$HOST_NAME.pem" -key-file "$CERT_DIR/$HOST_NAME-key.pem" "$HOST_NAME" >/dev/null 2>&1
			fi
			# Use a unique config name for each host
			CONFIG_FILE="$CERT_DIR/traefik-$HOST_NAME.yml"
			echo -e "tls:\n  certificates:\n    - certFile: /etc/traefik/certs/$HOST_NAME.pem\n      keyFile: /etc/traefik/certs/$HOST_NAME-key.pem" >"$CONFIG_FILE"

			setup_infrastructure "$RESOLVED_IP" "$SSL_PORT" "$LIFERAY_ROOT"
		fi
	fi

	L_TAG="$IMAGE_NAME:$LIFERAY_TAG"
	docker pull "$L_TAG"
	docker create -it "${NETWORK_ARGS[@]}" --name "${CONTAINER_NAME}" ${JVM_OPTS:+"-e LIFERAY_JVM_OPTS=$JVM_OPTS"} "${TRAEFIK_LABELS[@]}" -v "${FILES_VOLUME}:/mnt/liferay/files" -v "$LIFERAY_ROOT/scripts:/mnt/liferay/scripts" -v "${STATE_VOLUME}:/opt/liferay/osgi/state" -v "$LIFERAY_ROOT/osgi/modules:/opt/liferay/modules" -v "$LIFERAY_ROOT/data:/opt/liferay/data" -v "$LIFERAY_ROOT/deploy:/mnt/liferay/deploy" -v "$LIFERAY_ROOT/osgi/client-extensions:/opt/liferay/osgi/client-extensions" "$L_TAG"
else
	info_custom "${BYELLOW}=== Resuming $CONTAINER_NAME ==="
	[[ -n "$REMOVE_AFTER_FLAG" ]] && REMOVE_CONTAINER=Y || read_config "Remove container afterwards" REMOVE_CONTAINER N
	[[ -n "$DELETE_STATE_FLAG" ]] && RS=Y || read_config "Delete OSGi state folder" RS Y
	if [[ "${RS:u}" == "Y" ]]; then
		DELETE_STATE=1
		if docker ps -q --filter "name=^${CONTAINER_NAME}$" | grep -q .; then
			info "Stopping $CONTAINER_NAME to clear state..."
			STOP_OUT=$(docker stop "$CONTAINER_NAME" 2>&1)
			if [[ $? -ne 0 ]]; then
				error "Failed to stop container: $STOP_OUT"
				error "Aborting OSGi state deletion to prevent volume corruption."
				DELETE_STATE=0
			else
				if ! wait_for_container_stop "$CONTAINER_NAME"; then
					error "Container failed to stop within timeout."
					error "Aborting OSGi state deletion to prevent volume corruption."
					DELETE_STATE=0
				else
					sleep 2
				fi
			fi
		fi
		if [[ $DELETE_STATE -eq 1 ]]; then
			info "Clearing OSGi state..."
			rm -rf "$STATE_VOLUME" 2>/dev/null
			mkdir -p "$STATE_VOLUME"
		fi
	fi
	# Re-detect USE_SSL for success message on resume
	USE_SSL=0
	[[ "$(read_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "ssl")" == "1" ]] && USE_SSL=1
fi

CURRENT_JDBC_URL=$(grep "^jdbc.default.url=" "$FILES_VOLUME/portal-ext.properties" 2>/dev/null | cut -d'=' -f2-)
write_meta "$LIFERAY_ROOT/$PROJECT_META_FILE" "tag" "$LIFERAY_TAG" "port" "$LOCAL_PORT" "db_type" "$LIFERAY_DATABASE" "container_name" "$CONTAINER_NAME" "host_network" "$USE_HOST_NETWORK" "host_name" "$HOST_NAME" "es_port" "$ES_PORT" "jdbc_url" "$CURRENT_JDBC_URL" "ssl" "$USE_SSL" "last_run" "$(date -Iseconds)"

if [[ $FOLLOW_FLAG -eq 1 ]]; then
	docker start -i -a "${CONTAINER_NAME}" || { [[ "$(docker inspect -f '{{.State.ExitCode}}' $CONTAINER_NAME)" == "130" ]] || exit $?; }
else
	info "Starting ${CONTAINER_NAME}..."
	docker start "${CONTAINER_NAME}" >/dev/null || exit $?
	PROTO="http"
	ACCESS_PORT=":$LOCAL_PORT"
	if [[ $USE_SSL -eq 1 ]]; then
		PROTO="https"
		if [[ "$SSL_PORT" == "443" ]]; then ACCESS_PORT=""; else ACCESS_PORT=":$SSL_PORT"; fi
	fi
	access_url="${PROTO}://${HOST_NAME:-localhost}${ACCESS_PORT}"

	# --- Wait for Health Check ---
	info "Waiting for Liferay to start (this may take 2-5 minutes)..."
	START_TIME=$(date +%s)
	TIMEOUT=600
	IS_READY=0
	while (($(date +%s) - START_TIME < TIMEOUT)); do
		if curl -k -I "$access_url" 2>/dev/null | grep -qE "HTTP/.* (200|302)"; then
			IS_READY=1
			break
		fi
		echo -n "."
		sleep 10
	done
	echo -e "\n"

	if [[ $IS_READY -eq 1 ]]; then
		info_custom "${Green}✅ Container ${CONTAINER_NAME} is READY!"
	else
		error "Liferay is taking longer than expected to respond. Check logs for details."
	fi

	info_custom "  ${White}🌐 URL:            ${Cyan}${access_url}"
	info_custom "  ${White}📄 Logs:           ${Cyan}docker logs -f ${CONTAINER_NAME}"

	CLEANUP_MAIN="docker rm -f ${CONTAINER_NAME}"
	info_custom "  ${White}🛑 To stop and delete this demo: ${Cyan}${CLEANUP_MAIN}"
	[[ $USE_SSL -eq 1 ]] && info_custom "  ${White}🛑 To stop everything (including proxy): ${Cyan}${CLEANUP_MAIN} liferay-proxy-global"

	echo -e "\n${White}Notice a bug or have a feature request? Please report it on GitHub at:"
	echo -e "${Cyan}https://github.com/peterrichards-lr/liferay-docker-scripts${Color_Off}"
fi
[[ "${REMOVE_CONTAINER:u}" == "Y" ]] && {
	info "Deleting $CONTAINER_NAME"
	docker rm --force "$CONTAINER_NAME" >/dev/null 2>&1
}
