include-and-override=portal-developer.properties

browser.launcher.url=
cache.filter.include.user.agent=false
com.liferay.portal.servlet.filters.cache.CacheFilter=false
passwords.default.policy.change.required=false
session.timeout=120
setup.wizard.enabled=false
terms.of.use.required=false
users.reminder.queries.enabled=false

company.login.prepopulate.domain=false
company.security.strangers.with.mx=false
company.security.auto.login=false
company.security.strangers=false
company.security.strangers.verify=false
company.security.send.password.reset.link=false
company.security.update.password.required=false

layout.user.private.layouts.enabled=false
layout.user.private.layouts.auto.create=false
layout.user.public.layouts.enabled=false
layout.user.public.layouts.auto.create=false

field.enable.com.liferay.portal.kernel.model.Contact.male=false
field.enable.com.liferay.portal.kernel.model.Contact.birthday=false

feature.flag.ui.visible[dev]=true